name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sportsacademy-artifact
        path: target/

  docker:
    runs-on: ubuntu-latest
    needs: java
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and Push Docker Image to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
       context: .
       file: Dockerfile
       push: true
       tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}sportsacademy-latest
      env:
        DOCKER_BUILDKIT: 1
    - name: Add image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}sportsacademy-latest
        push: true
